### ISSUE TITLE
Update and Add to Eugene Tech Meetups Section

### ISSUE THREAD

**Issue by bauski** [eugenewebdevs/website#10]
At the bottom of the Eugene Web Devs homepage, we have a section called "Eugene Tech meetups". Some of the information on there is incorrect now, and there are more meetups that we should be adding to the section.

Add the following meetups:
* https://www.meetup.com/eugene-maker-space/events/245039787/
* https://www.meetup.com/Eugene-Cybersecurity/events/244525313/
* https://www.meetup.com/Bitforest/events/pklrwlywpbfc/

Update the following meetup:
* Eugene Womens Tech Meetup location is now Noisette, time is "First Wednesday of every month @ 5:30pm"
* Tech Tuesday Meetup time is "Every Tuesday @ 5:30pm"

**Comment by antonioortegajr** [comment]
This ticket is pretty old so if anyone picks this up probably a good idea to resist the AC here in a comment.

**Comment by yvesgurcan** [comment]
What do you mean by "Resist the AC"?

**Comment by antonioortegajr** [comment]
meant revisit, updated comment

**Comment by antonioortegajr** [comment]
closing this as am rebuilding the site
