### ISSUE TITLE
Rebuild website planning

### ISSUE THREAD

**Issue by antonioortegajr** [eugenewebdevs/website#23]
Possible candidate https://vuesion.herokuapp.com/ I like the idea of going the pwa direction.

**Comment by yvesgurcan** [comment]
How about Gatsby + GitHub Pages? :)

**Comment by antonioortegajr** [comment]
@yvesgurcan Changed title. Add any further suggestions.

**Comment by yvesgurcan** [comment]
We can use Gatsby (https://www.gatsbyjs.org/) and Styled Components (https://www.styled-components.com/) to create a fully static website.

The compiled build (https://www.gatsbyjs.org/docs/quick-start/#create-a-production-build) can be hosted directly in the repositor.

Serving the updated website at https://eugenewebdevs.com/ will necessitate work involving DNS redirections and a `CNAME` file present at the root of the repo (https://help.github.com/en/articles/managing-a-custom-domain-for-your-github-pages-site). The difficulty of that task will depend on the provider that hosts the website. See example with NameCheap: https://www.namecheap.com/support/knowledgebase/article.aspx/9645/2208/how-do-i-link-my-domain-to-github-pages.

**Comment by antonioortegajr** [comment]
Likely going to use a rebuild as an example for a talk.
