### ISSUE TITLE
Add CNAME to git ignore

### ISSUE THREAD

**Issue by antonioortegajr** [eugenewebdevs/website#33]
The CNAME file should not be changed by contributors so this should be included in gitignore

**Comment by Hyraze** [comment]
Add `CNAME ` in .gitignore

**Comment by antonioortegajr** [comment]
@Hyraze Thanks! That is is exactly what is needed.

Also: So the issue is here for new contributors. This repo and a few other repos around town leave straight forward issues for anyone wanting to do a pull request for the first time. SO it's less about any code fix ups and more about learning the git flow and we have a real issue to guide them with on the first go.

**Comment by Hyraze** [comment]
@antonioortegajr  Sorry to say, there isn't any way for now to stop "CNAME" from being forked since it is a remote repository..The  only thing that you can ace is to have a well documentation about the way to deal with "CNAME".

**Comment by antonioortegajr** [comment]
@Hyraze OK, will label this a invalid/close and create doc issue for this CNAME. Thanks!!
